matrix:
  include:
#    - os: linux
#      jdk: oraclejdk8
#      env: PYTHON_VERSION="2.7"
#    - os: linux
#      jdk: oraclejdk9
#      env: PYTHON_VERSION="2.7"
#    - os: linux
#      jdk: openjdk8
#      env: PYTHON_VERSION="2.7"
    - os: osx
      osx_image: xcode9.4
      env:
        - PYTHON_VERSION="2.7"
        - LIST_JAVAHOME=1
#    - os: osx
#      osx_image: xcode9.2
#      env: PYTHON_VERSION="2.7"
#    - os: linux
#      jdk: oraclejdk8
#      env: PYTHON_VERSION="3.5"
#    - os: linux
#      jdk: oraclejdk9
#      env: PYTHON_VERSION="3.5"
#    - os: linux
#      jdk: openjdk8
#      env: PYTHON_VERSION="3.5"
#    - os: osx
#      osx_image: xcode9.4
#      env: PYTHON_VERSION="3.5"
#    - os: osx
#      osx_image: xcode9.2
#      env: PYTHON_VERSION="3.5"

language: java

before_install:
   # Get the tag if it wasn't provided. Travis doesn't provide this if it isn't a tagged build.
   - if [ -z $TRAVIS_TAG ]; then TRAVIS_TAG=`git tag --contains` ; fi
   - echo $TRAVIS_TAG
   # Move out of git directory to build root.
   - cd ../..
   - pwd
install:
   # Download and configure conda.
   - |
     if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
     wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
     else
     wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
     fi
   - |
     if [[ "$LIST_JAVAHOME" == "1" ]]; then
     ls /Library/Internet\ Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/lib/server
     fi
   - bash miniconda.sh -b -p $HOME/miniconda
   - export PATH="$HOME/miniconda/bin:$PATH"
   - conda config --set always_yes yes
   - conda config --set show_channel_urls True
   - source activate root
   # Install basic conda dependencies.
   - |
     if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
     touch $HOME/miniconda/conda-meta/pinned;
     echo "conda-build ==1.16.0" >> $HOME/miniconda/conda-meta/pinned;
     fi
   - |
     if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
     conda install -c anaconda openjdk
     fi
   - conda update --all
   - conda install conda-build
   # Setup environment for testing and install all dependencies and our package.
   - cd $TRAVIS_REPO_SLUG
   - conda create --use-local -n testenv python=$PYTHON_VERSION
   - source activate testenv
   - python setup.py develop
   - python -c 'from javabridge import start_vm, kill_vm;start_vm();kill_vm()'
   - python -c 'from javabridge.jutil import _find_mac_lib;print(_find_mac_lib("libjvm"))'
   # Install sphinx and friends to build documentation.
   # (LEEK) travis install of sphinx on Python 3.5 crashed
   - pip install sphinx==1.7.2
   # Install coverage and coveralls to generate and submit test coverage results for coveralls.io.
   - echo "coverage 3.*" >> $HOME/miniconda/envs/testenv/conda-meta/pinned
   - conda install nose
   - conda install coverage
   - pip install coveralls
   # Clean up downloads as there are quite a few and they waste space/memory.
   - conda clean -tipsy
   - rm -rfv $HOME/.cache/pip
script:
   # Run tests.
   - python setup.py nosetests
   # Build docs.
   - cd docs
   - make html
   - cd ..
after_success:
   # Submit results to coveralls.io.
   - coveralls
# Use container format for TravisCI for quicker startup and builds.
sudo: false
